// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZF_UzwfOPBvCYWII00K3uKIroEMDpJK0',
    appId: '1:1033048145875:web:6b3c2c9522df97d33b3926',
    messagingSenderId: '1033048145875',
    projectId: 'chatapp-3e16a',
    authDomain: 'chatapp-3e16a.firebaseapp.com',
    storageBucket: 'chatapp-3e16a.appspot.com',
    measurementId: 'G-EP8CVM889M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmFW8uzCxh158RFk06z8zGEpJ3FAblAzE',
    appId: '1:1033048145875:android:eb539d084a452d233b3926',
    messagingSenderId: '1033048145875',
    projectId: 'chatapp-3e16a',
    storageBucket: 'chatapp-3e16a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRjEzCp6EPiyxSdAfVuzJn2LU__m_ZIXY',
    appId: '1:1033048145875:ios:4b3c9c6f49d3656e3b3926',
    messagingSenderId: '1033048145875',
    projectId: 'chatapp-3e16a',
    storageBucket: 'chatapp-3e16a.appspot.com',
    iosClientId: '1033048145875-ovbn4v6kdddi6tfgsgjjsosur3o0urul.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRjEzCp6EPiyxSdAfVuzJn2LU__m_ZIXY',
    appId: '1:1033048145875:ios:4b3c9c6f49d3656e3b3926',
    messagingSenderId: '1033048145875',
    projectId: 'chatapp-3e16a',
    storageBucket: 'chatapp-3e16a.appspot.com',
    iosClientId: '1033048145875-ovbn4v6kdddi6tfgsgjjsosur3o0urul.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
